version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/hosts:/etc/hosts
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/www/public
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./data/db:/data/db
      - ./data/logs:/data/logs
    expose:
        - "27017"
    command: mongod --smallfiles # --quiet
  login:
    depends_on:
      - nginx
    build: ./login
    expose:
      - "3000"
    environment:
      - NODE_PORT=3000
      - MONGO_PORT=27017
    volumes:
      - ./login/package.json:/app/package.json
      - ./login/src:/app/src
    command: "npm run dev"
