version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/hosts:/etc/hosts
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/www/public
  login:
    depends_on:
      - nginx
    build: ./login
    expose:
      - "3000"
    environment:
      - NODE_PORT=3000
      - MONGO_PORT=27017
    volumes:
      - ./login/package.json:/app/package.json
      - ./login/src:/app/src
    command: "npm run dev"
