version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/hosts:/etc/hosts
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/www
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./data/db:/data/db
      - ./data/logs:/data/logs
    expose:
        - "27017"
    command: mongod --smallfiles # --quiet
