version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/hosts:/etc/hosts
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/www/public
  mongodb:
    build: ./mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./data/db:/data/db
      - ./data/logs:/data/logs
    expose:
        - "27017"
    command: mongod --smallfiles # --quiet
  webpack:
    build: ./frontend
    volumes:
      - ./frontend/app:/opt/app
      - ./public:/opt/bin
    command: tail -f /dev/null
